### ISSUE TITLE
Unbuild with GCC 4.8

### ISSUE THREAD

**Issue by v-nikulichev** [nickhutchinson/libdispatch#17]
```
$ cat test.cpp 
#include <dispatch/dispatch.h>

int main()
{
    return 0;
}
```

```
$ g++ -I /opt/libdispatch/include -L /opt/libdispatch/lib test.cpp -ldispatch
In file included from /opt/libdispatch/include/dispatch/dispatch.h:50:0,
                 from test.cpp:1:
/opt/libdispatch/include/dispatch/object.h:102:3: error: template specialization with C linkage
   template <> struct is_dispatch_object<name##_s> : true_type {}; \
   ^
/opt/libdispatch/include/dispatch/data.h:42:1: note: in expansion of macro ‘DISPATCH_DECL’
 DISPATCH_DECL(dispatch_data);
 ^
/opt/libdispatch/include/dispatch/object.h:102:3: error: template specialization with C linkage
   template <> struct is_dispatch_object<name##_s> : true_type {}; \
   ^
/opt/libdispatch/include/dispatch/io.h:256:1: note: in expansion of macro ‘DISPATCH_DECL’
 DISPATCH_DECL(dispatch_io);
 ^
```
```
$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by nickhutchinson** [comment]
This should be fixed 0.1.2.
